In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [54]:
movies.sample(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3763,4000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,1809,"[{""id"": 128, ""name"": ""love triangle""}, {""id"": ...",en,The Rules of Attraction,The incredibly spoiled and overprivileged stud...,11.387335,"[{""name"": ""Kingsgate Films"", ""id"": 770}]","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2002-10-11,0,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,We all run on instinct,The Rules of Attraction,6.3,168

In [55]:
credits.sample(1)['crew'].values

array(['[{"credit_id": "52fe4544c3a36847f80c4711", "department": "Camera", "gender": 2, "id": 7413, "job": "Director of Photography", "name": "Mark Irwin"}, {"credit_id": "52fe4544c3a36847f80c46f9", "department": "Production", "gender": 2, "id": 19292, "job": "Executive Producer", "name": "Adam Sandler"}, {"credit_id": "552c568d92514138760010b3", "department": "Writing", "gender": 2, "id": 20818, "job": "Writer", "name": "Allen Covert"}, {"credit_id": "52fe4544c3a36847f80c474d", "department": "Production", "gender": 2, "id": 20819, "job": "Producer", "name": "Peter Dante"}, {"credit_id": "52fe4544c3a36847f80c46f3", "department": "Production", "gender": 2, "id": 20821, "job": "Executive Producer", "name": "Jack Giarraputo"}, {"credit_id": "52fe4544c3a36847f80c47a9", "department": "Art", "gender": 2, "id": 20824, "job": "Production Design", "name": "Perry Andelin Blake"}, {"credit_id": "52fe4544c3a36847f80c4717", "department": "Art", "gender": 2, "id": 32903, "job": "Art Direction", "name": "Alan Au"}, {"credit_id": "52fe4544c3a36847f80c46ff", "department": "Production", "gender": 2, "id": 32907, "job": "Producer", "name": "Nick Swardson"}, {"credit_id": "552c5696c3a368618e00106b", "department": "Writing", "gender": 2, "id": 32907, "job": "Writer", "name": "Nick Swardson"}, {"credit_id": "52fe4544c3a36847f80c46e1", "department": "Production", "gender": 2, "id": 41328, "job": "Executive Producer", "name": "Edward Milstein"}, {"credit_id": "52fe4544c3a36847f80c470b", "department": "Production", "gender": 2, "id": 41330, "job": "Executive Producer", "name": "Paul Schwake"}, {"credit_id": "52fe4544c3a36847f80c4705", "department": "Production", "gender": 2, "id": 11000, "job": "Executive Producer", "name": "Bill Todman Jr."}, {"credit_id": "52fe4544c3a36847f80c471d", "department": "Art", "gender": 0, "id": 45294, "job": "Art Direction", "name": "Lars Canty"}, {"credit_id": "52fe4544c3a36847f80c4753", "department": "Production", "gender": 2, "id": 59922, "job": "Executive Producer", "name": "Glenn S. Gainor"}, {"credit_id": "552c56a2925141387d0011bc", "department": "Writing", "gender": 2, "id": 60148, "job": "Writer", "name": "Barry Wernick"}, {"credit_id": "52fe4544c3a36847f80c46ed", "department": "Directing", "gender": 2, "id": 60149, "job": "Director", "name": "Nicholaus Goossen"}, {"credit_id": "52fe4544c3a36847f80c4723", "department": "Sound", "gender": 2, "id": 60150, "job": "Original Music Composer", "name": "Waddy Wachtel"}, {"credit_id": "52fe4544c3a36847f80c4729", "department": "Editing", "gender": 2, "id": 60151, "job": "Editor", "name": "Tom Costain"}, {"credit_id": "52fe4544c3a36847f80c472f", "department": "Production", "gender": 1, "id": 60154, "job": "Casting", "name": "Catherine Stroud"}, {"credit_id": "52fe4544c3a36847f80c473b", "department": "Costume & Make-Up", "gender": 1, "id": 60157, "job": "Costume Design", "name": "Maya Lieberman"}, {"credit_id": "52fe4544c3a36847f80c4741", "department": "Art", "gender": 0, "id": 60155, "job": "Art Direction", "name": "Jeffrey Mossa"}, {"credit_id": "52fe4544c3a36847f80c4747", "department": "Art", "gender": 0, "id": 60156, "job": "Set Decoration", "name": "Claire Kaufman"}, {"credit_id": "552d723992514159980005c3", "department": "Visual Effects", "gender": 0, "id": 1395352, "job": "Visual Effects Producer", "name": "Craig Sost"}, {"credit_id": "560a619b9251417191001eea", "department": "Production", "gender": 1, "id": 1516479, "job": "Casting", "name": "Lisa London"}]'],
      dtype=object)

In [56]:
movies = movies.merge(credits, on='title')

In [57]:
movies.sample(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
3099,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,91076,"[{""id"": 10965, ""name"": ""playwright""}, {""id"": 1...",en,Illuminata,"It's the start of the 20th century, and Tuccio...",0.111313,"[{""name"": ""Overseas FilmGroup"", ""id"": 888}, {""...",...,119.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Illuminata,6.3,7,91076,"[{""cast_id"": 10, ""character"": ""Tuccio"", ""credi...","[{""credit_id"": ""52fe48c39251416c750b276f"", ""de..."
2248,21000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.sonyclassics.com/synecdocheny,4960,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5756,...",en,"Synecdoche, New York","A theater director struggles with his work, an...",12.761176,"[{""name"": ""Likely Story"", ""id"": 1785}]",...,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Synecdoche, New York",7.4,278,4960,"[{""cast_id"": 3, ""character"": ""Caden Cotard"", ""...","[{""credit_id"": ""52fe43e8c3a36847f80777e3"", ""de..."

In [58]:
# feature selection
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast','crew']]

In [59]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
4284,46415,Neal 'n' Nikki,"The film, as its name implies, centres on Gurn...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 4344, ""name"": ""musical""}]","[{""cast_id"": 4, ""character"": ""Gurneal \""Neal\""...","[{""credit_id"": ""52fe46f6c3a36847f811c031"", ""de..."
234,49519,The Croods,The Croods is a prehistoric comedy adventure t...,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 16, ""...","[{""id"": 4428, ""name"": ""stone age""}, {""id"": 560...","[{""cast_id"": 3, ""character"": ""Grug Crood (voic...","[{""credit_id"": ""52fe4799c3a36847f813e52f"", ""de..."
3165,660,Thunderball,A criminal organization has obtained two nucle...,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 90, ""name"": ""paris""}, {""id"": 1196, ""na...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe4265c3a36847f801b5ad"", ""de..."
53,217,Indiana Jones and the Kingdom of the Crystal S...,"Set during the Cold War, the Soviets – led by ...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...","[{""cast_id"": 4, ""character"": ""Indiana Jones"", ...","[{""credit_id"": ""52fe4227c3a36847f800847d"", ""de..."
473,75,Mars Attacks!,'We come in peace' is not what those green men...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 14, ""nam...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...","[{""cast_id"": 6, ""character"": ""President James ...","[{""credit_id"": ""52fe4214c3a36847f80022fd"", ""de..."

In [60]:
 movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [61]:
movies.dropna(inplace=True)

In [62]:
movies.duplicated().sum()

np.int64(0)

In [63]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [64]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [65]:
movies['genres'] = movies['genres'].apply(convert)

In [66]:
movies['keywords'] = movies['keywords'].apply(convert)

In [67]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [68]:
movies['cast'] = movies['cast'].apply(convert3)

In [69]:
def fetch_director(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [70]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [71]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [72]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [73]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(' ', '') for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(' ', '') for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(' ', '') for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(' ', '') for i in x])

In [74]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [75]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [76]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [77]:
new_df = movies[['movie_id', 'title', 'tags']]

In [78]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Kumkum\AppData\Local\Temp\ipykernel_1240\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [79]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [80]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Kumkum\AppData\Local\Temp\ipykernel_1240\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [81]:
import nltk

In [82]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [83]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [84]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Kumkum\AppData\Local\Temp\ipykernel_1240\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [85]:
ps.stem('activity')

'activ'

In [86]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [87]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [88]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [89]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [90]:
from sklearn.metrics.pairwise import cosine_similarity

In [91]:
similarity = cosine_similarity(vectors)

In [92]:
sorted(list(enumerate(similarity[0])), reverse = True, key=lambda x:x[1])[1:6]

[(1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.25038669783359574))]

In [93]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [94]:
recommend('Batman Begins')

The Dark Knight
Batman
Batman
The Dark Knight Rises
10th & Wolf

In [95]:
new_df.iloc[1216].title

'Autumn in New York'

In [104]:
import pickle

In [105]:
movie_dict = new_df.to_dict()

In [106]:
pickle.dump(movie_dict, open('movie_dict.pkl', 'wb'))

In [107]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))